### ISSUE TITLE
Possible to set white balance on a per-pad basis?

### ISSUE THREAD

**Issue by gsxdsm** [Ableton/push-interface#13]
I'd like to adjust the individual pad white balances, but it seems like the current implementation only allows setting the white balance for an entire group?

**Comment by rsu-ableton** [comment]
Beginning with firmware 1.0.55 we have an internal mechanism to adjust the white balance for the current batch of LEDs, as well as two groups of pads with their own white balance in case two LED batches are mixed. Both mechanisms are configured in the factory and therefore the API is not published (to avoid overwriting the factory settings and losing the information). For performance and resource limitation reasons it is not possible to have more than these two groups of pad colors.

If your problem is that you see two kinds of whites, please contact our support,
maybe the colors can be adjusted a little.
