### ISSUE TITLE
Interface with Push 1

### ISSUE THREAD

**Issue by codenakama** [Ableton/push-interface#19]
Hi,

I would like to know if the interface described here applies to Push 1 as well or if there are at least common parts.

👍

**Comment by rsu-ableton** [comment]
The notes and CCs are kept as compatible as possible between Push1 and 2. The sysex is completely different, because Push 1 is engineered by Akai Pro and actually has quite different internal functions and configurability, as far as we know. This knowledge is owned by Akai and therefore we can't publish a MIDI spec for it. 

Maybe this nice blog by Marcelo Dantas could help:
http://pushmod.blogspot.com/

**Comment by codenakama** [comment]
@rsu-ableton can you let me know if the logic to render images/video on the push1 screens is maintained as well? cheers

**Comment by rsu-ableton** [comment]
Push1 has a character display with 8x5 red LED pixels per character (IIRC), filled from an ASCII character table using sysex, as described in the blog post mentioned above. Push2 has an LCD dot-matrix color display of 960x160 pixels which is filled using a separate USB bulk data port as described in the interface document.
